services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      CLUSTER_ID: 'ciWo7jRxS_iSee_pCo1i3g'
      KAFKA_CREATE_TOPICS: "sensor_data:1:1"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  publisher:
    build: ./publisher
    depends_on:
      - kafka
    environment:
      - SENSOR_HOSTNAME=

  subscriber:
    build: ./subscriber
    depends_on:
      - kafka
      - mongodb
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example

volumes:
  mongo-data:
